adapter: mysql2  
host: 192.168.2.89
port: 41767                          # VM Port 
database: t             # Database Name
username: anagjhw57u6n2ham                 # User Name
password: 'a360vjs2fswpm23s1ru29cuvkwape6gh'                # Password 
