adapter: mysql2  
host: 192.168.2.53
port: 63164                          # VM Port 
database: t             # Database Name
username: a0fj4x1jfs3vipiq                 # User Name
password: 'a3zg8llphpbgu9ud9xur6z6rb6u7kega'                # Password 
